import type { Part, PartVariant } from '@/lib/schemas';

const NOVA = { vehicleIds: ['veh-nova-1970'] };
const P = 'purchased-stock-model';

const part = (p: Omit<Part, 'provenance'>): Part => ({ ...p, provenance: P });

/** Editable components of the 1970 Nova SS 396 (purchased stock asset).
 *  The source model merges left/right pairs into single meshes, so paired
 *  panels are edited as pairs. */
export const NOVA_PARTS: Part[] = [
  part({
    id: 'part-nova-body',
    name: 'Body shell (roof & quarters)',
    category: 'body-panel',
    meshNodeIds: ['fender_b'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: null,
    removable: false,
  }),
  part({
    id: 'part-nova-front-clip',
    name: 'Front fenders (pair)',
    category: 'fender',
    meshNodeIds: ['fender_f'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-nova-front-clip',
    removable: true,
  }),
  part({
    id: 'part-nova-hood',
    name: 'Hood',
    category: 'hood',
    meshNodeIds: ['hood'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-nova-hood',
    removable: true,
  }),
  part({
    id: 'part-nova-hood-vents',
    name: 'SS hood vent inserts',
    category: 'accessory',
    meshNodeIds: ['hood_cell_chrome', 'hood_cell_plastic'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'trim-black'],
    socketId: 'socket-nova-hood-vents',
    removable: true,
  }),
  part({
    id: 'part-nova-cowl-vent',
    name: 'Cowl vent panel',
    category: 'body-panel',
    meshNodeIds: ['air_cell'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-doors',
    name: 'Doors (pair, with hardware)',
    category: 'door',
    meshNodeIds: ['door', 'door_handle', 'door_keyhole', 'door_keyhole01'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body', 'chrome', 'steel'],
    socketId: 'socket-nova-doors',
    removable: true,
  }),
  part({
    id: 'part-nova-trunk-lid',
    name: 'Trunk lid',
    category: 'body-panel',
    meshNodeIds: ['tailgate'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-nova-trunk',
    removable: true,
  }),
  part({
    id: 'part-nova-underbody',
    name: 'Underbody',
    category: 'chassis',
    meshNodeIds: ['bottom'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['trim-black'],
    socketId: null,
    removable: false,
  }),
  part({
    id: 'part-nova-engine-bay',
    name: 'Radiator',
    category: 'engine-bay',
    meshNodeIds: ['radiator'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['trim-black'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-exhaust',
    name: 'Exhaust pipe',
    category: 'exhaust',
    meshNodeIds: ['pipe'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['steel'],
    socketId: 'socket-nova-exhaust',
    removable: true,
  }),
  part({
    id: 'part-nova-bumper-front',
    name: 'Front bumper',
    category: 'bumper',
    meshNodeIds: ['bumper_f'],
    compatibility: NOVA,
    variantIds: ['var-nova-bumper-front-chrome', 'var-nova-bumper-front-painted'],
    defaultVariantId: 'var-nova-bumper-front-chrome',
    materialZoneIds: ['chrome'],
    socketId: 'socket-nova-bumper-front',
    removable: true,
  }),
  part({
    id: 'part-nova-bumper-rear',
    name: 'Rear bumper',
    category: 'bumper',
    meshNodeIds: ['bumper_b'],
    compatibility: NOVA,
    variantIds: ['var-nova-bumper-rear-chrome', 'var-nova-bumper-rear-painted'],
    defaultVariantId: 'var-nova-bumper-rear-chrome',
    materialZoneIds: ['chrome'],
    socketId: 'socket-nova-bumper-rear',
    removable: true,
  }),
  part({
    id: 'part-nova-grille',
    name: 'Grille assembly',
    category: 'grille',
    meshNodeIds: ['grill_chrome', 'grill_metal', 'grill_plastic'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'steel', 'trim-black'],
    socketId: 'socket-nova-grille',
    removable: true,
  }),
  part({
    id: 'part-nova-rear-panel',
    name: 'Rear valance grid',
    category: 'body-panel',
    meshNodeIds: ['grid_b'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['trim-black'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-trim',
    name: 'Mouldings & trim',
    category: 'trim',
    meshNodeIds: [
      'molding',
      'window_molding_chrome',
      'nichrome_05',
      'nichrome_06',
      'nichrome_07',
      'nichrome_08',
      'nichrome_09',
      'nichrome_10',
    ],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'trim-black'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-headlights',
    name: 'Headlights',
    category: 'lights',
    meshNodeIds: ['headlight_f_1_glass01', 'headlight_f_1_reflector01'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['lights-clear', 'chrome'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-front-signals',
    name: 'Front turn signals',
    category: 'lights',
    meshNodeIds: ['signal_f_body', 'signal_f_glass'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'lights-amber'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-parking-lights',
    name: 'Parking lights',
    category: 'lights',
    meshNodeIds: ['ptf_glass', 'ptf_reflector', 'ptf_refractor'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['lights-clear', 'chrome'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-taillights',
    name: 'Tail light assemblies',
    category: 'lights',
    meshNodeIds: [
      'taillight_chrome',
      'taillight_glass_red',
      'taillight_glass_clear',
      'taillight_refractor',
      'signal_b_body',
      'signal_b_glass',
    ],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'lights-red', 'lights-clear'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-light-bulbs',
    name: 'Light bulbs & sockets',
    category: 'lights',
    meshNodeIds: [
      'sphere_body35',
      'sphere_body36',
      'sphere_body37',
      'sphere_body38',
      'sphere_body39',
      'sphere_body40',
      'sphere_lightbulb05',
      'sphere_lightbulb06',
      'sphere_lightbulb07',
      'sphere_lightbulb08',
      'sphere_lightbulb09',
      'sphere_lightbulb10',
    ],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['steel', 'lights-clear', 'lights-amber'],
    socketId: null,
    removable: false,
  }),
  part({
    id: 'part-nova-glass',
    name: 'Glass (all windows)',
    category: 'glass',
    meshNodeIds: ['window_glass'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['glass'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-mirror',
    name: 'Door mirror',
    category: 'mirror',
    meshNodeIds: ['mirror_body', 'mirror_glass'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'mirror'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-interior-mirror',
    name: 'Interior mirror',
    category: 'mirror',
    meshNodeIds: ['interior_mirror', 'interior_mirror_mirror', 'interior_mirror_part'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['trim-black', 'mirror', 'chrome'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-wipers',
    name: 'Wipers',
    category: 'accessory',
    meshNodeIds: ['wiper_l_chrome', 'wiper_r_chrome', 'wiper_l_gum', 'wiper_r_gum'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'trim-black'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-badges',
    name: 'Badges & scripts',
    category: 'trim',
    meshNodeIds: [
      'logo_f_p1',
      'logo_f_p2',
      'logo_f_p3',
      'logo_nova_b_p1',
      'logo_nova_b_p2',
      'logo_nova_b_p3',
      'logo_ss_b',
      'logo_ss_f',
      'text_396',
      'text_397',
      'text_nova_f_l',
      'text_nova_f_r',
    ],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome', 'trim-black', 'badge-blue', 'badge-red'],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-plates',
    name: 'Licence plates',
    category: 'accessory',
    meshNodeIds: ['LicPlate01', 'LicPlate02'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: [],
    socketId: null,
    removable: true,
  }),
  part({
    id: 'part-nova-interior',
    name: 'Interior (seats & dash)',
    category: 'interior',
    meshNodeIds: ['interior_chairs', 'interior_torpedo'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['interior'],
    socketId: null,
    removable: false,
  }),
  part({
    id: 'part-nova-brakes',
    name: 'Brake discs',
    category: 'brakes',
    meshNodeIds: ['brakedisk_f_l', 'brakedisk_f_r', 'brakedisk_b_l', 'brakedisk_b_r'],
    compatibility: NOVA,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['brake'],
    socketId: null,
    removable: false,
  }),
  // Installed by default; while installed, the parametric wheel/stance system
  // is suspended for this vehicle (see Wheels/Stance tabs). Remove it to use
  // configurable wheels, tyres and stance.
  part({
    id: 'part-nova-oem-wheelset',
    name: 'Factory wheel & tyre set',
    category: 'wheel',
    meshNodeIds: [
      'tire_f_l',
      'tire_f_r',
      'tire_b_l',
      'tire_b_r',
      'rim_p1_f_l',
      'rim_p1_f_r',
      'rim_p1_b_l',
      'rim_p1_b_r',
      'rim_p2_f_l',
      'rim_p2_f_r',
      'rim_p2_b_l',
      'rim_p2_b_r',
      'rim_p3_f_l',
      'rim_p3_f_r',
      'rim_p3_b_l',
      'rim_p3_b_r',
      'rim_p4_f_l',
      'rim_p4_f_r',
      'rim_p4_b_l',
      'rim_p4_b_r',
      'rim_p5_f_l',
      'rim_p5_f_r',
      'rim_p5_b_l',
      'rim_p5_b_r',
      'rim_bolt_f_l',
      'rim_bolt_f_r',
      'rim_bolt_b_l',
      'rim_bolt_b_r',
      'rim_nipel_f_l',
      'rim_nipel_f_r',
      'rim_nipel_b_l',
      'rim_nipel_b_r',
    ],
    compatibility: NOVA,
    variantIds: ['var-nova-oem-wheelset'],
    defaultVariantId: 'var-nova-oem-wheelset',
    materialZoneIds: ['rim', 'tyre'],
    socketId: 'socket-nova-wheels',
    removable: true,
  }),
];

export const NOVA_VARIANTS: PartVariant[] = [
  {
    id: 'var-nova-oem-wheelset',
    partId: 'part-nova-oem-wheelset',
    name: 'Factory SS wheels',
    visual: {
      kind: 'mesh-swap',
      visibleNodeIds: NOVA_PARTS.find((p) => p.id === 'part-nova-oem-wheelset')!.meshNodeIds,
    },
    provenance: P,
  },
  {
    id: 'var-nova-bumper-front-chrome',
    partId: 'part-nova-bumper-front',
    name: 'Chrome',
    visual: { kind: 'material-override' },
    provenance: P,
  },
  {
    id: 'var-nova-bumper-front-painted',
    partId: 'part-nova-bumper-front',
    name: 'Body-colour painted',
    visual: { kind: 'material-override', useBodyColor: true, metallic: 0.15, roughness: 0.4 },
    priceEstimateUsd: 260,
    provenance: P,
  },
  {
    id: 'var-nova-bumper-rear-chrome',
    partId: 'part-nova-bumper-rear',
    name: 'Chrome',
    visual: { kind: 'material-override' },
    provenance: P,
  },
  {
    id: 'var-nova-bumper-rear-painted',
    partId: 'part-nova-bumper-rear',
    name: 'Body-colour painted',
    visual: { kind: 'material-override', useBodyColor: true, metallic: 0.15, roughness: 0.4 },
    priceEstimateUsd: 260,
    provenance: P,
  },
];
