import type { AssetManifest } from '@/lib/schemas';

/**
 * Asset manifest for the 1970 Chevrolet Nova SS 396 (purchased stock model,
 * Standard License). The GLB is NOT committed to this repository — a standard
 * stock-model licence does not permit public redistribution of the source
 * asset. Place the file locally at `public/assets/vehicles/nova-1970.glb`
 * (see README); until then the vehicle shows a truthful missing-asset state.
 *
 * Node names come from the purchased asset and are sometimes misleading:
 * `fender_b` is the full body shell including roof and quarters, `fender_f`
 * is the front clip, `air_cell`/`hood_cell_*` are cowl/hood vent panels.
 * Left/right pairs are merged into single meshes by the source model.
 */
export const NOVA_MANIFEST: AssetManifest = {
  id: 'manifest-nova-1970',
  schemaVersion: 1,
  source: {
    type: 'gltf',
    uri: '/assets/vehicles/nova-1970.glb',
    sizeBytes: 32257880,
    compression: 'none',
  },
  // UV-mapped variant of the same purchased asset (converted from the
  // seller's UV update via scripts/convert-nova-uv-to-glb.mjs — same licence,
  // also not committed). Preferred at runtime when present; enables liveries.
  liverySource: {
    type: 'gltf',
    uri: '/assets/vehicles/nova-1970-uv.glb',
    sizeBytes: 33297664,
    compression: 'none',
  },
  // Project-original add-on parts (scoops, spoilers) fitted to this vehicle;
  // CC0 and committed to the repo, unlike the licensed base model.
  addonSource: {
    type: 'gltf',
    uri: '/assets/vehicles/nova-addons.glb',
    compression: 'none',
  },
  attribution: {
    sourceName: 'Purchased stock 3D model (Hum3D-style marketplace)',
    creator: 'Third-party stock artist',
    licence: 'Standard License (purchased)',
    attributionText:
      'Chevrolet Nova Mk3 SS 396 1970 stock 3D model, purchased under a Standard License. Not redistributable; asset file is excluded from the public repository.',
    reuseConfirmed: true,
  },
  scale: 1,
  units: 'm',
  coordinateSystem: 'y-up-z-forward',
  supportedFeatures: {
    componentEditing: true,
    materialZones: true,
    explodedView: true,
    wheelSwap: true,
    stance: true,
  },
  lods: [],
  meshNodes: [
    // --- Body (paintable) ---------------------------------------------------
    { nodeName: 'fender_b', componentId: 'part-nova-body', materialZoneId: 'body' },
    {
      nodeName: 'fender_f',
      componentId: 'part-nova-front-clip',
      materialZoneId: 'body',
      explodeOffset: [0, 0.15, 0.55],
    },
    {
      nodeName: 'hood',
      componentId: 'part-nova-hood',
      materialZoneId: 'hood',
      explodeOffset: [0, 0.55, 0.3],
    },
    {
      nodeName: 'door',
      componentId: 'part-nova-doors',
      materialZoneId: 'body',
      explodeOffset: [0, 0.1, 0.45],
    },
    {
      nodeName: 'tailgate',
      componentId: 'part-nova-trunk-lid',
      materialZoneId: 'body',
      explodeOffset: [0, 0.45, -0.55],
    },
    {
      nodeName: 'air_cell',
      componentId: 'part-nova-cowl-vent',
      materialZoneId: 'body',
      explodeOffset: [0, 0.35, 0],
    },
    // --- Underbody / chassis ------------------------------------------------
    {
      nodeName: 'bottom',
      componentId: 'part-nova-underbody',
      materialZoneId: 'trim-black',
      explodeOffset: [0, -0.4, 0],
    },
    {
      nodeName: 'radiator',
      componentId: 'part-nova-engine-bay',
      materialZoneId: 'trim-black',
      explodeOffset: [0, 0.3, 0.4],
    },
    {
      nodeName: 'pipe',
      componentId: 'part-nova-exhaust',
      materialZoneId: 'steel',
      explodeOffset: [0, -0.3, -0.4],
    },
    // --- Bumpers, grille, brightwork ---------------------------------------
    {
      nodeName: 'bumper_f',
      componentId: 'part-nova-bumper-front',
      materialZoneId: 'bumper-front',
      explodeOffset: [0, 0, 0.7],
    },
    {
      nodeName: 'bumper_b',
      componentId: 'part-nova-bumper-rear',
      materialZoneId: 'bumper-rear',
      explodeOffset: [0, 0, -0.7],
    },
    {
      nodeName: 'grill_chrome',
      componentId: 'part-nova-grille',
      materialZoneId: 'grille',
      explodeOffset: [0, 0, 0.55],
    },
    {
      nodeName: 'grill_metal',
      componentId: 'part-nova-grille',
      materialZoneId: 'grille',
      explodeOffset: [0, 0, 0.55],
    },
    {
      nodeName: 'grill_plastic',
      componentId: 'part-nova-grille',
      materialZoneId: 'trim-black',
      explodeOffset: [0, 0, 0.55],
    },
    {
      nodeName: 'grid_b',
      componentId: 'part-nova-rear-panel',
      materialZoneId: 'trim-black',
      explodeOffset: [0, 0, -0.5],
    },
    {
      nodeName: 'molding',
      componentId: 'part-nova-trim',
      materialZoneId: 'trim',
      explodeOffset: [0, 0.1, 0],
    },
    {
      nodeName: 'window_molding_chrome',
      componentId: 'part-nova-trim',
      materialZoneId: 'trim',
      explodeOffset: [0, 0.2, 0],
    },
    { nodeName: 'nichrome_05', componentId: 'part-nova-trim', materialZoneId: 'trim-black' },
    { nodeName: 'nichrome_06', componentId: 'part-nova-trim', materialZoneId: 'trim-black' },
    { nodeName: 'nichrome_07', componentId: 'part-nova-trim', materialZoneId: 'trim-black' },
    { nodeName: 'nichrome_08', componentId: 'part-nova-trim', materialZoneId: 'trim-black' },
    { nodeName: 'nichrome_09', componentId: 'part-nova-trim', materialZoneId: 'trim-black' },
    { nodeName: 'nichrome_10', componentId: 'part-nova-trim', materialZoneId: 'trim-black' },
    // --- Hood vent (SS hood inserts) ---------------------------------------
    {
      nodeName: 'hood_cell_chrome',
      componentId: 'part-nova-hood-vents',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0.6, 0.3],
    },
    {
      nodeName: 'hood_cell_plastic',
      componentId: 'part-nova-hood-vents',
      materialZoneId: 'trim-black',
      explodeOffset: [0, 0.6, 0.3],
    },
    // --- Lights -------------------------------------------------------------
    {
      nodeName: 'headlight_f_1_glass01',
      componentId: 'part-nova-headlights',
      materialZoneId: 'lights-clear',
      explodeOffset: [0, 0.05, 0.5],
    },
    {
      nodeName: 'headlight_f_1_reflector01',
      componentId: 'part-nova-headlights',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0.05, 0.5],
    },
    {
      nodeName: 'signal_f_body',
      componentId: 'part-nova-front-signals',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0, 0.45],
    },
    {
      nodeName: 'signal_f_glass',
      componentId: 'part-nova-front-signals',
      materialZoneId: 'lights-amber',
      explodeOffset: [0, 0, 0.45],
    },
    {
      nodeName: 'ptf_glass',
      componentId: 'part-nova-parking-lights',
      materialZoneId: 'lights-clear',
      explodeOffset: [0, -0.05, 0.45],
    },
    {
      nodeName: 'ptf_reflector',
      componentId: 'part-nova-parking-lights',
      materialZoneId: 'chrome',
      explodeOffset: [0, -0.05, 0.45],
    },
    {
      nodeName: 'ptf_refractor',
      componentId: 'part-nova-parking-lights',
      materialZoneId: 'lights-clear',
      explodeOffset: [0, -0.05, 0.45],
    },
    {
      nodeName: 'taillight_chrome',
      componentId: 'part-nova-taillights',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0, -0.5],
    },
    {
      nodeName: 'taillight_glass_red',
      componentId: 'part-nova-taillights',
      materialZoneId: 'lights-red',
      explodeOffset: [0, 0, -0.5],
    },
    {
      nodeName: 'taillight_glass_clear',
      componentId: 'part-nova-taillights',
      materialZoneId: 'lights-clear',
      explodeOffset: [0, 0, -0.5],
    },
    {
      nodeName: 'taillight_refractor',
      componentId: 'part-nova-taillights',
      materialZoneId: 'lights-clear',
      explodeOffset: [0, 0, -0.5],
    },
    {
      nodeName: 'signal_b_body',
      componentId: 'part-nova-taillights',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0, -0.5],
    },
    {
      nodeName: 'signal_b_glass',
      componentId: 'part-nova-taillights',
      materialZoneId: 'lights-red',
      explodeOffset: [0, 0, -0.5],
    },
    { nodeName: 'sphere_body35', componentId: 'part-nova-light-bulbs', materialZoneId: 'steel' },
    { nodeName: 'sphere_body36', componentId: 'part-nova-light-bulbs', materialZoneId: 'steel' },
    { nodeName: 'sphere_body37', componentId: 'part-nova-light-bulbs', materialZoneId: 'steel' },
    { nodeName: 'sphere_body38', componentId: 'part-nova-light-bulbs', materialZoneId: 'steel' },
    { nodeName: 'sphere_body39', componentId: 'part-nova-light-bulbs', materialZoneId: 'steel' },
    { nodeName: 'sphere_body40', componentId: 'part-nova-light-bulbs', materialZoneId: 'steel' },
    {
      nodeName: 'sphere_lightbulb05',
      componentId: 'part-nova-light-bulbs',
      materialZoneId: 'lights-clear',
    },
    {
      nodeName: 'sphere_lightbulb06',
      componentId: 'part-nova-light-bulbs',
      materialZoneId: 'lights-amber',
    },
    {
      nodeName: 'sphere_lightbulb07',
      componentId: 'part-nova-light-bulbs',
      materialZoneId: 'lights-clear',
    },
    {
      nodeName: 'sphere_lightbulb08',
      componentId: 'part-nova-light-bulbs',
      materialZoneId: 'lights-clear',
    },
    {
      nodeName: 'sphere_lightbulb09',
      componentId: 'part-nova-light-bulbs',
      materialZoneId: 'lights-clear',
    },
    {
      nodeName: 'sphere_lightbulb10',
      componentId: 'part-nova-light-bulbs',
      materialZoneId: 'lights-clear',
    },
    // --- Glass, mirrors, wipers ---------------------------------------------
    {
      nodeName: 'window_glass',
      componentId: 'part-nova-glass',
      materialZoneId: 'glass',
      explodeOffset: [0, 0.4, 0],
    },
    // Window glass panes split off during the seller's UV work — these two
    // nodes exist only in the UV-mapped liverySource asset.
    {
      nodeName: 'Object001',
      componentId: 'part-nova-glass',
      materialZoneId: 'glass',
      explodeOffset: [0, 0.4, 0],
    },
    {
      nodeName: 'Object002',
      componentId: 'part-nova-glass',
      materialZoneId: 'glass',
      explodeOffset: [0, 0.4, 0],
    },
    {
      nodeName: 'mirror_body',
      componentId: 'part-nova-mirror',
      materialZoneId: 'chrome',
      explodeOffset: [0.3, 0.15, 0],
    },
    {
      nodeName: 'mirror_glass',
      componentId: 'part-nova-mirror',
      materialZoneId: 'mirror',
      explodeOffset: [0.3, 0.15, 0],
    },
    {
      nodeName: 'interior_mirror',
      componentId: 'part-nova-interior-mirror',
      materialZoneId: 'trim-black',
    },
    {
      nodeName: 'interior_mirror_mirror',
      componentId: 'part-nova-interior-mirror',
      materialZoneId: 'mirror',
    },
    {
      nodeName: 'interior_mirror_part',
      componentId: 'part-nova-interior-mirror',
      materialZoneId: 'chrome',
    },
    {
      nodeName: 'wiper_l_chrome',
      componentId: 'part-nova-wipers',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0.2, 0.1],
    },
    {
      nodeName: 'wiper_r_chrome',
      componentId: 'part-nova-wipers',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0.2, 0.1],
    },
    {
      nodeName: 'wiper_l_gum',
      componentId: 'part-nova-wipers',
      materialZoneId: 'trim-black',
      explodeOffset: [0, 0.2, 0.1],
    },
    {
      nodeName: 'wiper_r_gum',
      componentId: 'part-nova-wipers',
      materialZoneId: 'trim-black',
      explodeOffset: [0, 0.2, 0.1],
    },
    // --- Door hardware -------------------------------------------------------
    {
      nodeName: 'door_handle',
      componentId: 'part-nova-doors',
      materialZoneId: 'chrome',
      explodeOffset: [0, 0.1, 0.45],
    },
    {
      nodeName: 'door_keyhole',
      componentId: 'part-nova-doors',
      materialZoneId: 'steel',
      explodeOffset: [0, 0.1, 0.45],
    },
    {
      nodeName: 'door_keyhole01',
      componentId: 'part-nova-doors',
      materialZoneId: 'steel',
      explodeOffset: [0, 0.1, 0.45],
    },
    // --- Badges & plates -----------------------------------------------------
    { nodeName: 'logo_f_p1', componentId: 'part-nova-badges', materialZoneId: 'badge-blue' },
    { nodeName: 'logo_f_p2', componentId: 'part-nova-badges', materialZoneId: 'trim-black' },
    { nodeName: 'logo_f_p3', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    { nodeName: 'logo_nova_b_p1', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    { nodeName: 'logo_nova_b_p2', componentId: 'part-nova-badges', materialZoneId: 'trim-black' },
    { nodeName: 'logo_nova_b_p3', componentId: 'part-nova-badges', materialZoneId: 'badge-red' },
    { nodeName: 'logo_ss_b', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    { nodeName: 'logo_ss_f', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    { nodeName: 'text_396', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    { nodeName: 'text_397', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    { nodeName: 'text_nova_f_l', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    { nodeName: 'text_nova_f_r', componentId: 'part-nova-badges', materialZoneId: 'chrome' },
    {
      nodeName: 'LicPlate01',
      componentId: 'part-nova-plates',
      materialZoneId: null,
      explodeOffset: [0, 0, 0.5],
    },
    {
      nodeName: 'LicPlate02',
      componentId: 'part-nova-plates',
      materialZoneId: null,
      explodeOffset: [0, 0, -0.5],
    },
    // --- Interior ------------------------------------------------------------
    {
      nodeName: 'interior_chairs',
      componentId: 'part-nova-interior',
      materialZoneId: 'interior',
      explodeOffset: [0, 0.5, 0],
    },
    {
      nodeName: 'interior_torpedo',
      componentId: 'part-nova-interior',
      materialZoneId: 'interior',
      explodeOffset: [0, 0.5, 0.15],
    },
    // --- Brakes --------------------------------------------------------------
    { nodeName: 'brakedisk_f_l', componentId: 'part-nova-brakes', materialZoneId: 'brake' },
    { nodeName: 'brakedisk_f_r', componentId: 'part-nova-brakes', materialZoneId: 'brake' },
    { nodeName: 'brakedisk_b_l', componentId: 'part-nova-brakes', materialZoneId: 'brake' },
    { nodeName: 'brakedisk_b_r', componentId: 'part-nova-brakes', materialZoneId: 'brake' },
    // --- Add-on parts (project-original nova-addons.glb) ---------------------
    {
      nodeName: 'cowl_scoop_2in',
      componentId: 'part-nova-cowl-scoop',
      materialZoneId: 'hood',
      explodeOffset: [0, 0.5, 0.3],
    },
    {
      nodeName: 'cowl_scoop_4in',
      componentId: 'part-nova-cowl-scoop',
      materialZoneId: 'hood',
      explodeOffset: [0, 0.5, 0.3],
    },
    {
      nodeName: 'chin_spoiler',
      componentId: 'part-nova-chin-spoiler',
      materialZoneId: 'body',
      explodeOffset: [0, -0.15, 0.6],
    },
    {
      nodeName: 'trunk_spoiler_ducktail',
      componentId: 'part-nova-trunk-spoiler',
      materialZoneId: 'body',
      explodeOffset: [0, 0.4, -0.5],
    },
    {
      nodeName: 'trunk_spoiler_wing',
      componentId: 'part-nova-trunk-spoiler',
      materialZoneId: 'body',
      explodeOffset: [0, 0.4, -0.5],
    },
    // --- Factory wheel & tyre set (hidden when parametric wheels are used) ---
    ...[
      'tire_f_l',
      'tire_f_r',
      'tire_b_l',
      'tire_b_r',
      'rim_p1_f_l',
      'rim_p1_f_r',
      'rim_p1_b_l',
      'rim_p1_b_r',
      'rim_p2_f_l',
      'rim_p2_f_r',
      'rim_p2_b_l',
      'rim_p2_b_r',
      'rim_p3_f_l',
      'rim_p3_f_r',
      'rim_p3_b_l',
      'rim_p3_b_r',
      'rim_p4_f_l',
      'rim_p4_f_r',
      'rim_p4_b_l',
      'rim_p4_b_r',
      'rim_p5_f_l',
      'rim_p5_f_r',
      'rim_p5_b_l',
      'rim_p5_b_r',
      'rim_bolt_f_l',
      'rim_bolt_f_r',
      'rim_bolt_b_l',
      'rim_bolt_b_r',
      'rim_nipel_f_l',
      'rim_nipel_f_r',
      'rim_nipel_b_l',
      'rim_nipel_b_r',
    ].map((nodeName) => ({
      nodeName,
      componentId: 'part-nova-oem-wheelset',
      materialZoneId: nodeName.startsWith('tire') ? 'tyre' : 'rim',
    })),
  ],
  materialZones: [
    {
      id: 'body',
      label: 'Body',
      defaultColorHex: '#316f8b',
      defaultFinish: { metallic: 0.15, roughness: 0.4, clearcoat: 0.7 },
      paintable: true,
    },
    {
      id: 'interior',
      label: 'Interior',
      defaultColorHex: '#656565',
      defaultFinish: { metallic: 0, roughness: 0.7, clearcoat: 0 },
      paintable: true,
    },
    {
      id: 'hood',
      label: 'Hood',
      defaultColorHex: '#316f8b',
      defaultFinish: { metallic: 0.15, roughness: 0.4, clearcoat: 0.7 },
      paintable: true,
    },
    {
      id: 'bumper-front',
      label: 'Front bumper',
      defaultColorHex: '#c9cdd3',
      defaultFinish: { metallic: 1, roughness: 0.1, clearcoat: 0 },
      paintable: true,
    },
    {
      id: 'bumper-rear',
      label: 'Rear bumper',
      defaultColorHex: '#c9cdd3',
      defaultFinish: { metallic: 1, roughness: 0.1, clearcoat: 0 },
      paintable: true,
    },
    {
      id: 'grille',
      label: 'Grille',
      defaultColorHex: '#b9bdc4',
      defaultFinish: { metallic: 1, roughness: 0.15, clearcoat: 0 },
      paintable: true,
    },
    {
      id: 'trim',
      label: 'Trim mouldings',
      defaultColorHex: '#c9cdd3',
      defaultFinish: { metallic: 1, roughness: 0.12, clearcoat: 0 },
      paintable: true,
    },
    {
      id: 'glass',
      label: 'Glass',
      defaultColorHex: '#dfe9e7',
      defaultFinish: { metallic: 0, roughness: 0.02, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'chrome',
      label: 'Chrome & brightwork',
      defaultColorHex: '#8a8a8a',
      defaultFinish: { metallic: 1, roughness: 0.1, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'trim-black',
      label: 'Black trim & plastics',
      defaultColorHex: '#111214',
      defaultFinish: { metallic: 0, roughness: 0.55, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'steel',
      label: 'Bare metal',
      defaultColorHex: '#d5d5d5',
      defaultFinish: { metallic: 0.8, roughness: 0.4, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'mirror',
      label: 'Mirror glass',
      defaultColorHex: '#c8d6d2',
      defaultFinish: { metallic: 1, roughness: 0.02, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'lights-clear',
      label: 'Clear lenses',
      defaultColorHex: '#f4f4f4',
      defaultFinish: { metallic: 0, roughness: 0.02, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'lights-red',
      label: 'Red lenses',
      defaultColorHex: '#fe5a45',
      defaultFinish: { metallic: 0, roughness: 0.02, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'lights-amber',
      label: 'Amber lenses',
      defaultColorHex: '#e68a3c',
      defaultFinish: { metallic: 0, roughness: 0.02, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'rim',
      label: 'Factory rims',
      defaultColorHex: '#adadad',
      defaultFinish: { metallic: 0.9, roughness: 0.3, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'tyre',
      label: 'Factory tyres',
      defaultColorHex: '#141414',
      defaultFinish: { metallic: 0, roughness: 0.85, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'brake',
      label: 'Brake discs',
      defaultColorHex: '#7d7d7d',
      defaultFinish: { metallic: 0.7, roughness: 0.4, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'badge-blue',
      label: 'Badge blue',
      defaultColorHex: '#1f1f8a',
      defaultFinish: { metallic: 0, roughness: 0.25, clearcoat: 0 },
      paintable: false,
    },
    {
      id: 'badge-red',
      label: 'Badge red',
      defaultColorHex: '#ae0000',
      defaultFinish: { metallic: 0, roughness: 0.3, clearcoat: 0 },
      paintable: false,
    },
  ],
  // Model "left" is +X. Well clearances are estimates from the fender openings.
  wheelAnchors: [
    {
      id: 'FL',
      axle: 'front',
      side: 'left',
      position: [0.794, 0.343, 1.707],
      wellClearanceRadiusM: 0.4,
      wellClearanceWidthM: 0.28,
    },
    {
      id: 'FR',
      axle: 'front',
      side: 'right',
      position: [-0.794, 0.343, 1.707],
      wellClearanceRadiusM: 0.4,
      wellClearanceWidthM: 0.28,
    },
    {
      id: 'RL',
      axle: 'rear',
      side: 'left',
      position: [0.817, 0.346, -1.192],
      wellClearanceRadiusM: 0.42,
      wellClearanceWidthM: 0.3,
    },
    {
      id: 'RR',
      axle: 'rear',
      side: 'right',
      position: [-0.817, 0.346, -1.192],
      wellClearanceRadiusM: 0.42,
      wellClearanceWidthM: 0.3,
    },
  ],
  // Shader-painted racing stripes may cover these paintable zones.
  stripeZones: ['body', 'hood'],
  // Livery graphics (roundels, lettering) drawn on the liverySource UV atlas.
  liveryZones: ['body', 'hood'],
  // Island frames for pre-designed schemes: one affine car-space→UV map per
  // atlas island (each full body side is a single island — verified by
  // cross-predicting fender/quarter vertex UVs from the door frame, errors
  // < 0.001 UV). Emitted by scripts/probe-nova-livery-anchors.mjs.
  liveryPanels: [
    {
      id: 'side-l',
      origin: [0.9343, 0.7214, 0.3057],
      rightDir: [0, 0, -1],
      upDir: [0, 1, 0],
      uv: [0.4326, 0.628],
      rightUvPerM: [0.2029, 0.0003],
      upUvPerM: [-0.0005, 0.2015],
    },
    {
      id: 'side-r',
      origin: [-0.9343, 0.7214, 0.3057],
      rightDir: [0, 0, 1],
      upDir: [0, 1, 0],
      uv: [0.5617, 0.8562],
      rightUvPerM: [0.2029, -0.0003],
      upUvPerM: [0.0005, 0.2015],
    },
    {
      id: 'hood',
      origin: [0, 0.98, 1.1892],
      rightDir: [1, 0, 0],
      upDir: [0, 0, -1],
      uv: [0.264, 0.3596],
      rightUvPerM: [0, -0.189],
      upUvPerM: [0.1973, 0],
    },
    {
      id: 'roof',
      origin: [0, 1.4412, -0.3232],
      rightDir: [1, 0, 0],
      upDir: [0, 0, -1],
      uv: [0.5703, 0.3596],
      rightUvPerM: [0, -0.2038],
      upUvPerM: [0.203, 0],
    },
    {
      id: 'trunk',
      origin: [0, 1.1194, -1.6397],
      rightDir: [-1, 0, 0],
      upDir: [0, 0, 1],
      uv: [0.8369, 0.3596],
      rightUvPerM: [0, 0.2018],
      upUvPerM: [-0.195, 0],
    },
  ],
  // Anchor UVs + local UV-per-metre frames measured from the UV asset via
  // scripts/probe-nova-livery-anchors.mjs (the atlas is a clean affine
  // orthographic unwrap at ~0.20 UV per metre on every panel).
  liveryAnchors: [
    {
      id: 'door-l',
      label: 'Left door',
      kind: 'roundel',
      uv: [0.3932, 0.6317],
      rightUvPerM: [0.2029, 0.0003],
      upUvPerM: [-0.0005, 0.2015],
      sizeM: 0.46,
    },
    {
      id: 'door-r',
      label: 'Right door',
      kind: 'roundel',
      uv: [0.6011, 0.8599],
      rightUvPerM: [0.2029, -0.0003],
      upUvPerM: [0.0005, 0.2015],
      sizeM: 0.46,
    },
    {
      id: 'hood',
      label: 'Hood',
      kind: 'roundel',
      uv: [0.1928, 0.3596],
      rightUvPerM: [0, -0.189],
      upUvPerM: [0.1973, 0],
      sizeM: 0.55,
    },
    {
      id: 'roof',
      label: 'Roof',
      kind: 'roundel',
      uv: [0.5453, 0.3596],
      rightUvPerM: [0, -0.2038],
      upUvPerM: [0.203, 0],
      sizeM: 0.58,
    },
    {
      id: 'trunk',
      label: 'Trunk lid',
      kind: 'roundel',
      uv: [0.8779, 0.3596],
      rightUvPerM: [0, 0.2018],
      upUvPerM: [-0.195, 0],
      sizeM: 0.42,
    },
    {
      id: 'quarter-l',
      label: 'Left quarter',
      kind: 'lettering',
      uv: [0.859, 0.652],
      rightUvPerM: [0.2026, -0.0003],
      upUvPerM: [-0.0018, 0.2025],
      sizeM: 0.11,
    },
    {
      id: 'quarter-r',
      label: 'Right quarter',
      kind: 'lettering',
      uv: [0.1351, 0.8802],
      rightUvPerM: [0.2035, 0.0003],
      upUvPerM: [0.0009, 0.2025],
      sizeM: 0.11,
    },
    {
      id: 'fender-l',
      label: 'Left fender',
      kind: 'lettering',
      uv: [0.0915, 0.6425],
      rightUvPerM: [0.2003, 0.0017],
      upUvPerM: [0.014, 0.1922],
      sizeM: 0.09,
    },
    {
      id: 'fender-r',
      label: 'Right fender',
      kind: 'lettering',
      uv: [0.9038, 0.8707],
      rightUvPerM: [0.2017, -0.0017],
      upUvPerM: [-0.0079, 0.1922],
      sizeM: 0.09,
    },
  ],
  // Generated numberplates replace the baked LicPlate meshes (positions and
  // 520 x 110 mm size measured from the asset).
  plateMounts: [
    {
      id: 'front',
      componentId: 'part-nova-plates',
      position: [0, 0.4203, 2.452],
      rotationDeg: [0, 0, 0],
      widthM: 0.52,
      heightM: 0.11,
      hideNodeNames: ['LicPlate01'],
    },
    {
      id: 'rear',
      componentId: 'part-nova-plates',
      position: [0, 0.5679, -2.474],
      rotationDeg: [0, 180, 0],
      widthM: 0.52,
      heightM: 0.11,
      hideNodeNames: ['LicPlate02'],
    },
  ],
  cameraTargets: {
    defaultTarget: [0, 0.65, 0],
    defaultPosition: [4.4, 1.7, 5.2],
    presets: [
      { id: 'front', label: 'Front', position: [0, 1.0, 6.6], target: [0, 0.7, 0] },
      { id: 'rear', label: 'Rear', position: [0, 1.0, -6.6], target: [0, 0.7, 0] },
      { id: 'left', label: 'Left', position: [6.4, 1.1, 0], target: [0, 0.7, 0] },
      { id: 'right', label: 'Right', position: [-6.4, 1.1, 0], target: [0, 0.7, 0] },
      { id: 'three-quarter', label: '3/4 Front', position: [4.4, 1.7, 5.2], target: [0, 0.65, 0] },
      {
        id: 'three-quarter-rear',
        label: '3/4 Rear',
        position: [-4.4, 1.7, -5.2],
        target: [0, 0.65, 0],
      },
      { id: 'top', label: 'Top', position: [0, 8.6, 0.01], target: [0, 0.5, 0] },
      {
        id: 'detail-front-wheel',
        label: 'Front wheel',
        position: [2.3, 0.5, 2.5],
        target: [0.794, 0.343, 1.707],
      },
      {
        id: 'detail-grille',
        label: 'Grille detail',
        position: [1.3, 0.85, 3.6],
        target: [0, 0.6, 2.35],
      },
    ],
  },
  fitmentBounds: {
    overallLengthM: 4.98,
    overallWidthM: 1.9,
    overallHeightM: 1.44,
    trackWidthFrontM: 1.588,
    trackWidthRearM: 1.634,
    stockRideHeightM: 0,
    minRideHeightM: -0.1,
  },
};
