import type { Part, PartVariant } from '@/lib/schemas';

const DEMO = { vehicleIds: ['veh-tf100-1952'] };

/** Editable components of the TF-100 demo vehicle. All data-driven — the UI
 *  renders whatever appears here; nothing about the TF-100 is hard-coded. */
export const TF100_PARTS: Part[] = [
  {
    id: 'part-cab',
    name: 'Cab shell',
    category: 'cab',
    meshNodeIds: ['cab_shell'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: null,
    removable: false,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-roof',
    name: 'Roof panel',
    category: 'roof',
    meshNodeIds: ['roof_panel'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['roof'],
    socketId: null,
    removable: false,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-hood',
    name: 'Hood',
    category: 'hood',
    meshNodeIds: ['hood_stock', 'hood_scooped'],
    compatibility: DEMO,
    variantIds: ['var-hood-stock', 'var-hood-scooped'],
    defaultVariantId: 'var-hood-stock',
    materialZoneIds: ['body'],
    socketId: 'socket-hood',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-stripe',
    name: 'Hood stripe kit',
    category: 'accessory',
    meshNodeIds: ['stripe_hood'],
    compatibility: DEMO,
    variantIds: ['var-stripe-single'],
    defaultVariantId: null, // not installed on the stock build
    materialZoneIds: ['stripes'],
    socketId: 'socket-hood-stripe',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-door-left',
    name: 'Door (left)',
    category: 'door',
    meshNodeIds: ['door_left'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-door-left',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-door-right',
    name: 'Door (right)',
    category: 'door',
    meshNodeIds: ['door_right'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-door-right',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-fender-left',
    name: 'Front fender (left)',
    category: 'fender',
    meshNodeIds: ['fender_front_left'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-fender-left',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-fender-right',
    name: 'Front fender (right)',
    category: 'fender',
    meshNodeIds: ['fender_front_right'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-fender-right',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-bed',
    name: 'Stepside bed',
    category: 'bed',
    meshNodeIds: [
      'bed_side_left',
      'bed_side_right',
      'bed_floor',
      'rear_fender_left',
      'rear_fender_right',
    ],
    compatibility: { ...DEMO, bodyStyles: ['stepside'] },
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body', 'bed'],
    socketId: 'socket-bed',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-tailgate',
    name: 'Tailgate',
    category: 'tailgate',
    meshNodeIds: ['tailgate'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['body'],
    socketId: 'socket-tailgate',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-bumper-front',
    name: 'Front bumper',
    category: 'bumper',
    meshNodeIds: ['bumper_front'],
    compatibility: DEMO,
    variantIds: ['var-bumper-front-chrome', 'var-bumper-front-painted'],
    defaultVariantId: 'var-bumper-front-chrome',
    materialZoneIds: ['chrome'],
    socketId: 'socket-bumper-front',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-bumper-rear',
    name: 'Rear bumper',
    category: 'bumper',
    meshNodeIds: ['bumper_rear'],
    compatibility: DEMO,
    variantIds: ['var-bumper-rear-chrome', 'var-bumper-rear-painted'],
    defaultVariantId: 'var-bumper-rear-chrome',
    materialZoneIds: ['chrome'],
    socketId: 'socket-bumper-rear',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-grille',
    name: 'Grille',
    category: 'grille',
    meshNodeIds: ['grille_bars', 'grille_mesh'],
    compatibility: DEMO,
    variantIds: ['var-grille-bars', 'var-grille-mesh'],
    defaultVariantId: 'var-grille-bars',
    materialZoneIds: ['chrome'],
    socketId: 'socket-grille',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-headlights',
    name: 'Headlights',
    category: 'lights',
    meshNodeIds: ['headlight_left', 'headlight_right'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['lights'],
    socketId: null,
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-taillights',
    name: 'Tail lights',
    category: 'lights',
    meshNodeIds: ['taillight_left', 'taillight_right'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['lights-red'],
    socketId: null,
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-mirror',
    name: 'Door mirror (left)',
    category: 'mirror',
    meshNodeIds: ['mirror_left'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chrome'],
    socketId: null,
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-glass',
    name: 'Glass set',
    category: 'glass',
    meshNodeIds: ['glass_windshield', 'glass_rear', 'glass_side_left', 'glass_side_right'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['glass'],
    socketId: null,
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-running-boards',
    name: 'Running boards',
    category: 'trim',
    meshNodeIds: ['running_board_left', 'running_board_right'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['accent'],
    socketId: null,
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-chassis',
    name: 'Chassis frame',
    category: 'chassis',
    meshNodeIds: ['chassis_frame'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['chassis'],
    socketId: null,
    removable: false,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-exhaust',
    name: 'Exhaust',
    category: 'exhaust',
    meshNodeIds: ['exhaust_stock', 'exhaust_side_left', 'exhaust_side_right'],
    compatibility: DEMO,
    variantIds: ['var-exhaust-stock', 'var-exhaust-side-pipes'],
    defaultVariantId: 'var-exhaust-stock',
    materialZoneIds: ['steel', 'chrome'],
    socketId: 'socket-exhaust',
    removable: true,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-interior',
    name: 'Interior (bench seat & wheel)',
    category: 'interior',
    meshNodeIds: ['seat_bench', 'steering_wheel'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['interior'],
    socketId: null,
    removable: false,
    provenance: 'seed-catalogue',
  },
  {
    id: 'part-engine',
    name: 'Engine block',
    category: 'engine-bay',
    meshNodeIds: ['engine_block'],
    compatibility: DEMO,
    variantIds: [],
    defaultVariantId: null,
    materialZoneIds: ['steel'],
    socketId: 'socket-engine',
    removable: true,
    provenance: 'seed-catalogue',
  },
  // Wheels are configured per-axle in Wheels & Tyres; this part is the
  // catalogue holder for wheel variants and is not in the installed list.
  {
    id: 'part-wheel',
    name: 'Wheels',
    category: 'wheel',
    meshNodeIds: [],
    compatibility: {},
    variantIds: [
      'var-wheel-steelie',
      'var-wheel-smoothie',
      'var-wheel-five-spoke',
      'var-wheel-slot-mag',
      'var-wheel-rally',
    ],
    defaultVariantId: 'var-wheel-steelie',
    materialZoneIds: [],
    socketId: null,
    removable: false,
    provenance: 'seed-catalogue',
  },
];

export const TF100_VARIANTS: PartVariant[] = [
  {
    id: 'var-hood-stock',
    partId: 'part-hood',
    name: 'Stock hood',
    visual: { kind: 'mesh-swap', visibleNodeIds: ['hood_stock'] },
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-hood-scooped',
    partId: 'part-hood',
    name: 'Scooped hood',
    visual: { kind: 'mesh-swap', visibleNodeIds: ['hood_scooped'] },
    priceEstimateUsd: 680,
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-stripe-single',
    partId: 'part-stripe',
    name: 'Centre stripe',
    visual: { kind: 'mesh-swap', visibleNodeIds: ['stripe_hood'] },
    priceEstimateUsd: 90,
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-bumper-front-chrome',
    partId: 'part-bumper-front',
    name: 'Chrome',
    visual: { kind: 'material-override', colorHex: '#d8dadf', metallic: 1, roughness: 0.12 },
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-bumper-front-painted',
    partId: 'part-bumper-front',
    name: 'Body-colour painted',
    visual: { kind: 'material-override', useBodyColor: true, metallic: 0.1, roughness: 0.35 },
    priceEstimateUsd: 240,
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-bumper-rear-chrome',
    partId: 'part-bumper-rear',
    name: 'Chrome',
    visual: { kind: 'material-override', colorHex: '#d8dadf', metallic: 1, roughness: 0.12 },
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-bumper-rear-painted',
    partId: 'part-bumper-rear',
    name: 'Body-colour painted',
    visual: { kind: 'material-override', useBodyColor: true, metallic: 0.1, roughness: 0.35 },
    priceEstimateUsd: 240,
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-grille-bars',
    partId: 'part-grille',
    name: 'Horizontal bars',
    visual: { kind: 'mesh-swap', visibleNodeIds: ['grille_bars'] },
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-grille-mesh',
    partId: 'part-grille',
    name: 'Mesh insert',
    visual: { kind: 'mesh-swap', visibleNodeIds: ['grille_mesh'] },
    priceEstimateUsd: 320,
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-exhaust-stock',
    partId: 'part-exhaust',
    name: 'Stock single exit',
    visual: { kind: 'mesh-swap', visibleNodeIds: ['exhaust_stock'] },
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-exhaust-side-pipes',
    partId: 'part-exhaust',
    name: 'Side pipes',
    visual: { kind: 'mesh-swap', visibleNodeIds: ['exhaust_side_left', 'exhaust_side_right'] },
    priceEstimateUsd: 540,
    provenance: 'seed-catalogue',
  },
  {
    id: 'var-wheel-steelie',
    partId: 'part-wheel',
    name: 'Steelie',
    visual: { kind: 'procedural-wheel', style: 'steelie', finish: 'steel' },
    provenance: 'procedural',
  },
  {
    id: 'var-wheel-smoothie',
    partId: 'part-wheel',
    name: 'Smoothie',
    visual: { kind: 'procedural-wheel', style: 'smoothie', finish: 'body-color' },
    priceEstimateUsd: 640,
    provenance: 'procedural',
  },
  {
    id: 'var-wheel-five-spoke',
    partId: 'part-wheel',
    name: 'Five-spoke alloy',
    visual: { kind: 'procedural-wheel', style: 'five-spoke', finish: 'polished' },
    priceEstimateUsd: 980,
    provenance: 'procedural',
  },
  {
    id: 'var-wheel-slot-mag',
    partId: 'part-wheel',
    name: 'Slot mag',
    visual: { kind: 'procedural-wheel', style: 'slot-mag', finish: 'satin-black' },
    priceEstimateUsd: 860,
    provenance: 'procedural',
  },
  {
    id: 'var-wheel-rally',
    partId: 'part-wheel',
    name: 'Rally',
    visual: { kind: 'procedural-wheel', style: 'rally', finish: 'chrome' },
    priceEstimateUsd: 720,
    provenance: 'procedural',
  },
];
