import type { Vehicle } from '@/lib/schemas';

const NO_ASSET = 'No 3D asset available yet — browsable metadata only.';

/**
 * Seed vehicle catalogue (1948–1978 American classics). Real year/make/model
 * names are used as factual catalogue metadata only; the only entry with a 3D
 * asset is the project-original TF-100 demo vehicle. The catalogue is
 * representative, not historically complete.
 */
export const VEHICLES: Vehicle[] = [
  {
    id: 'veh-tf100-1952',
    year: 1952,
    make: 'Titanforge',
    model: 'TF-100 Stepside',
    trim: 'Demo',
    vehicleType: 'pickup',
    bodyStyle: 'stepside',
    cabStyle: 'standard',
    bedStyle: 'stepside',
    generation: 'Demo asset',
    dimensionsMm: { length: 4720, width: 1920, height: 1780, wheelbase: 2840 },
    tags: ['demo', 'truck', 'stepside', 'fully-editable'],
    description:
      'Project-original, stylised early-50s style stepside pickup. Not a model of any real production vehicle. Fully component-mapped: separate named meshes, material zones, wheel anchors and fitment metadata.',
    attribution: {
      sourceName: 'Project-original demo asset',
      creator: 'vehicle-build-config (procedurally generated)',
      licence: 'CC0-1.0',
      licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
      attributionText: 'Demo vehicle generated for vehicle-build-config; public domain (CC0).',
      reuseConfirmed: true,
    },
    assetManifestId: 'manifest-tf100',
    knownLimitations: [
      'Stylised demo geometry — proportions are representative, not measured from a real vehicle.',
      'Dimensions and clearances are indicative and not manufacturing-validated.',
    ],
  },
  {
    id: 'veh-nova-1970',
    year: 1970,
    make: 'Chevrolet',
    model: 'Nova',
    trim: 'SS 396',
    vehicleType: 'car',
    bodyStyle: 'coupe',
    generation: 'Third generation (Mk3)',
    dimensionsMm: { length: 4980, width: 1900, height: 1440, wheelbase: 2900 },
    tags: ['muscle', 'x-body', 'big-block', 'fully-editable'],
    description:
      'Third-generation Nova SS 396 coupe from a purchased, fully part-separated stock 3D model: 115 named meshes covering body panels, brightwork, lights, interior, badges and a factory wheel set.',
    attribution: {
      sourceName: 'Purchased stock 3D model (Hum3D-style marketplace)',
      creator: 'Third-party stock artist',
      licence: 'Standard License (purchased)',
      attributionText:
        'Chevrolet Nova Mk3 SS 396 1970 stock 3D model, purchased under a Standard License. Asset file is excluded from the public repository.',
      reuseConfirmed: true,
    },
    assetManifestId: 'manifest-nova-1970',
    knownLimitations: [
      'Model file is not committed to the public repository (Standard License) — place nova-1970.glb in public/assets/vehicles/ locally; see README.',
      'Left/right panel pairs (doors, fenders) are merged into single meshes by the source model, so they edit as pairs.',
      'While the factory wheel set is installed, parametric wheels/tyres/stance are suspended (remove it in the Parts tab or from the Wheels tab to configure them).',
      'No engine model in the source asset (radiator only); dimensions are display-asset measurements, not engineering data.',
    ],
  },
  {
    id: 'veh-belair-1957',
    year: 1957,
    make: 'Chevrolet',
    model: 'Bel Air',
    trim: 'Sport Coupe',
    vehicleType: 'car',
    bodyStyle: 'hardtop',
    generation: 'Tri-Five',
    dimensionsMm: { length: 5100, width: 1870, height: 1520, wheelbase: 2921 },
    tags: ['classic', 'tri-five', 'chrome'],
    description: 'Iconic Tri-Five hardtop with tailfins and chrome spears.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-mustang-1965',
    year: 1965,
    make: 'Ford',
    model: 'Mustang',
    trim: '2+2',
    vehicleType: 'car',
    bodyStyle: 'fastback',
    generation: 'First generation',
    dimensionsMm: { length: 4613, width: 1732, height: 1316, wheelbase: 2743 },
    tags: ['pony-car', 'fastback'],
    description: 'First-generation pony car in 2+2 fastback form.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-charger-1969',
    year: 1969,
    make: 'Dodge',
    model: 'Charger',
    trim: 'R/T',
    vehicleType: 'car',
    bodyStyle: 'hardtop',
    generation: 'B-body second generation',
    dimensionsMm: { length: 5280, width: 1948, height: 1358, wheelbase: 2972 },
    tags: ['muscle', 'b-body'],
    description: 'Second-generation B-body with hidden headlights and flying-buttress roofline.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-chevelle-1970',
    year: 1970,
    make: 'Chevrolet',
    model: 'Chevelle',
    trim: 'SS 454',
    vehicleType: 'car',
    bodyStyle: 'hardtop',
    generation: 'Second generation A-body',
    dimensionsMm: { length: 5029, width: 1918, height: 1339, wheelbase: 2845 },
    tags: ['muscle', 'big-block'],
    description: 'Peak-muscle A-body hardtop with cowl-induction hood option.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-3100-1953',
    year: 1953,
    make: 'Chevrolet',
    model: '3100',
    trim: 'Half-ton',
    vehicleType: 'pickup',
    bodyStyle: 'stepside',
    cabStyle: 'standard',
    bedStyle: 'stepside',
    generation: 'Advance Design',
    dimensionsMm: { length: 4877, width: 1938, height: 1918, wheelbase: 2946 },
    tags: ['truck', 'advance-design'],
    description: 'Advance Design half-ton pickup with five-bar horizontal grille.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-f100-1956',
    year: 1956,
    make: 'Ford',
    model: 'F-100',
    trim: 'Custom Cab',
    vehicleType: 'pickup',
    bodyStyle: 'stepside',
    cabStyle: 'standard',
    bedStyle: 'stepside',
    generation: 'Second generation F-Series',
    dimensionsMm: { length: 4813, width: 1918, height: 1905, wheelbase: 2794 },
    tags: ['truck', 'effie'],
    description: 'Wrap-around windshield year of the second-generation F-Series.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-c10-1967',
    year: 1967,
    make: 'Chevrolet',
    model: 'C10',
    trim: 'Fleetside',
    vehicleType: 'pickup',
    bodyStyle: 'fleetside',
    cabStyle: 'standard',
    bedStyle: 'fleetside',
    generation: 'Action Line',
    dimensionsMm: { length: 4737, width: 2007, height: 1755, wheelbase: 2921 },
    tags: ['truck', 'action-line'],
    description: 'First-year Action Line half-ton with low, wide fleetside bed.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-cuda-1971',
    year: 1971,
    make: 'Plymouth',
    model: "'Cuda",
    trim: '440',
    vehicleType: 'car',
    bodyStyle: 'hardtop',
    generation: 'E-body',
    dimensionsMm: { length: 4763, width: 1918, height: 1290, wheelbase: 2743 },
    tags: ['muscle', 'e-body'],
    description: 'E-body hardtop with quad headlights and fender gills.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-nomad-1955',
    year: 1955,
    make: 'Chevrolet',
    model: 'Nomad',
    vehicleType: 'wagon',
    bodyStyle: 'wagon',
    generation: 'Tri-Five',
    dimensionsMm: { length: 5004, width: 1880, height: 1521, wheelbase: 2921 },
    tags: ['wagon', 'two-door'],
    description: 'Two-door sport wagon with slanted B-pillars and ribbed tailgate.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-econoline-1961',
    year: 1961,
    make: 'Ford',
    model: 'Econoline',
    vehicleType: 'van',
    bodyStyle: 'van',
    generation: 'First generation',
    dimensionsMm: { length: 4293, width: 1791, height: 1956, wheelbase: 2286 },
    tags: ['van', 'forward-control'],
    description: 'Forward-control compact van on the Falcon platform.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-3800-1950',
    year: 1950,
    make: 'Chevrolet',
    model: '3800 Panel',
    vehicleType: 'panel-truck',
    bodyStyle: 'panel',
    cabStyle: 'standard',
    bedStyle: 'none',
    generation: 'Advance Design',
    dimensionsMm: { length: 5232, width: 1938, height: 2050, wheelbase: 3429 },
    tags: ['panel', 'delivery'],
    description: 'One-ton Advance Design panel delivery truck.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-superdeluxe-1948',
    year: 1948,
    make: 'Ford',
    model: 'Super De Luxe',
    trim: 'Club Coupe',
    vehicleType: 'car',
    bodyStyle: 'coupe',
    generation: '1941-48 body',
    dimensionsMm: { length: 5004, width: 1852, height: 1707, wheelbase: 2896 },
    tags: ['prewar-body', 'flathead'],
    description: 'Last year of the prewar-derived body with the flathead V8.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-trans-am-1977',
    year: 1977,
    make: 'Pontiac',
    model: 'Firebird Trans Am',
    vehicleType: 'car',
    bodyStyle: 'coupe',
    generation: 'Second generation F-body',
    dimensionsMm: { length: 4986, width: 1863, height: 1257, wheelbase: 2743 },
    tags: ['f-body', 'late-70s'],
    description: 'Second-generation F-body with shaker scoop.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
  {
    id: 'veh-impala-1962',
    year: 1962,
    make: 'Chevrolet',
    model: 'Impala',
    trim: 'SS',
    vehicleType: 'car',
    bodyStyle: 'convertible',
    generation: 'Third generation',
    dimensionsMm: { length: 5326, width: 2007, height: 1372, wheelbase: 3023 },
    tags: ['full-size', 'convertible', 'lowrider-favourite'],
    description: 'Full-size convertible, a lowrider and cruiser favourite.',
    assetManifestId: null,
    knownLimitations: [NO_ASSET],
  },
];
